Added code for Dynamic Programming Algorithms
Py-Contributors/AlgorithmsAndDataStructure pull request #949
Opened 2023-10-04 15:51 UTC by abhijeet147

`Please fill all the details and checkbox, so we can merge PR faster.`

## Pull Request Template

###  Added the code for Dynamic Programming Algorithms :
>>spiralmatrix
>>scheduling_algorithm (shortest_job_first)
>>pattern searching (duplicate_subtree)
>>pathfinding_algorithm

### Issue no.(must) - 946

Pr will be closed and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me if not it will marked as spam.
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.My code is well linted and I am using flake8 standard for python
- [x] I have added title and what program will do first in the file

## acknowledgment
- [x] I have tested the script and distributed it under an MIT license.

### README - [How to Contribute](https://github.com/Py-Contributors/AlgorithmsAndDataStructure/blob/master/CONTRIBUTING.md)
[SpiralMatrixzip.zip](https://github.com/Py-Contributors/AlgorithmsAndDataStructure/files/12805191/SpiralMatrixzip.zip)
[Schedulung_algorithmzip.zip](https://github.com/Py-Contributors/AlgorithmsAndDataStructure/files/12805194/Schedulung_algorithmzip.zip)
[Pattern_searchingzip.zip](https://github.com/Py-Contributors/AlgorithmsAndDataStructure/files/12805195/Pattern_searchingzip.zip)
[Pathfinding_algorithmzip.zip](https://github.com/Py-Contributors/AlgorithmsAndDataStructure/files/12805197/Pathfinding_algorithmzip.zip)

2023-10-06 16:44 UTC, cankush625 requested changes
Added comments for code quality. Not sure about the execution of these programs.

2023-10-06 16:44 UTC, cankush625 commented on SpiralMatrix.cpp
> +    cin >> no;
This should be accepted as a function parameter.

2023-10-06 16:44 UTC, cankush625 commented on SpiralMatrix.cpp
> +    int no;
Variables names can be meaningful.

2023-10-06 16:44 UTC, cankush625 commented on Duplicate_subtree.cpp
> +    s += ")";
Variable name can be better

2023-10-06 16:44 UTC, cankush625 commented on Duplicate_subtree.cpp
> +std::string inorder(Node* root, std::unordered_map<std::string, int>& m) {
Parameter name for `m` can be better

2023-10-12 04:50 UTC, codeperfectplus commented
Please make the @abhijeet147 changes as suggested by @cankush625.
We are focusing on better code quality now 
Thanks

2023-11-02 05:43 UTC, codeperfectplus commented
Don't add Zip files.

2023-11-02 07:25 UTC, Mr-vabs approved these changes
Seems good to go

2023-11-12 04:32 UTC, closed without merging